const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let step=0,busy=false;
const state={PC:'1000H',MAR:'—',MDR:'—',IR:'—',CU:'waiting',ACC:'05H',ALU:'—'};
const steps=[
{phase:'FETCH',title:'Where is the next instruction?',text:'The Program Counter remembers the address of the next instruction the CPU must fetch.',micro:'PC = 1000H\n“Next instruction is at address 1000H.”',active:['PC'],caption:'Start with one fact: PC contains an address, not the instruction itself.'},
{phase:'FETCH',title:'Give the address to MAR',text:'Before memory can be accessed, the address is copied into the Memory Address Register.',micro:'MAR ← PC\nMAR = 1000H',active:['PC','MAR'],move:{from:[142,145],to:[337,145],text:'1000H',kind:'address'},set:{MAR:'1000H'},caption:'MAR is the CPU’s “which memory location?” register.'},
{phase:'FETCH',title:'Which bus carries 1000H?',text:'The CPU now needs to send the memory location to main memory.',micro:'1000H must travel from MAR → Memory',active:['MAR'],question:{prompt:'Choose the correct bus:',choices:['Data Bus','Address Bus','Control Bus'],answer:1},caption:'Think: 1000H is a location. Which bus carries WHERE?'},
{phase:'FETCH',title:'Send the address to memory',text:'The Address Bus carries the address 1000H from the CPU to memory.',micro:'ADDRESS BUS = WHERE\nMAR → [1000H] → Memory',active:['MAR','addressBus'],move:{from:[410,145],to:[745,175],text:'1000H',kind:'address'},caption:'Address Bus tells memory WHERE the CPU wants to access.'},
{phase:'FETCH',title:'Memory knows where — but what should it do?',text:'An address alone is not enough. The Control Unit must tell memory whether the CPU wants to READ or WRITE.',micro:'CU → MEMORY READ → Memory',active:['CU','controlBus'],move:{from:[515,285],to:[745,300],text:'READ',kind:'control'},set:{CU:'MEMORY READ'},caption:'Control Bus carries the action: READ.'},
{phase:'FETCH',title:'Memory opens location 1000H',text:'Memory decodes the address and selects location 1000H. That location contains the instruction ADD 2050H.',micro:'Memory[1000H] = ADD 2050H',active:['mem1000'],caption:'The instruction has been found. Now it must travel back to the CPU.'},
{phase:'FETCH',title:'The instruction returns on the Data Bus',text:'Unlike 1000H, ADD 2050H is information. Memory sends it to the CPU through the Data Bus and MDR receives it.',micro:'Memory → DATA BUS → MDR\nMDR = ADD 2050H',active:['mem1000','dataBus','MDR'],move:{from:[745,220],to:[625,160],text:'ADD 2050H',kind:'data'},set:{MDR:'ADD 2050H'},caption:'Data Bus carries the actual instruction/data.'},
{phase:'FETCH',title:'Move the instruction into IR',text:'MDR is a temporary transfer register. The instruction is copied into the Instruction Register for decoding.',micro:'IR ← MDR\nIR = ADD 2050H',active:['MDR','IR'],move:{from:[542,160],to:[175,300],text:'ADD 2050H',kind:'data'},set:{IR:'ADD 2050H',PC:'1001H'},caption:'At the same time, PC advances to the next instruction: 1001H.'},
{phase:'DECODE',title:'Decode ADD 2050H',text:'The instruction separates into an opcode and an operand address. ADD tells the Control Unit what operation is required; 2050H tells it where the operand lives.',micro:'ADD     | 2050H\nOPCODE  | OPERAND ADDRESS',active:['IR','CU'],set:{CU:'decode: ADD'},caption:'ADD = what operation? 2050H = where is the operand?'},
{phase:'OPERAND',title:'Fetch the operand',text:'The instruction is decoded, but the CPU still does not have the number to add. It must perform a second memory read.',micro:'MAR ← 2050H',active:['IR','MAR'],move:{from:[175,300],to:[337,145],text:'2050H',kind:'address'},set:{MAR:'2050H'},caption:'This time MAR contains the operand address, not the instruction address.'},
{phase:'OPERAND',title:'Read Memory[2050H]',text:'2050H travels on the Address Bus and the Control Unit sends READ again. Memory location 2050H contains 03H.',micro:'Address = 2050H\nControl = READ\nMemory[2050H] = 03H',active:['MAR','addressBus','controlBus','mem2050'],move:{from:[410,145],to:[745,350],text:'2050H',kind:'address'},set:{CU:'MEMORY READ'},caption:'Same mechanism, different purpose: the first read fetched an instruction; this read fetches data.'},
{phase:'OPERAND',title:'03H enters the CPU',text:'The operand value 03H travels back through the Data Bus and is received by MDR.',micro:'MDR ← Memory[2050H]\nMDR = 03H',active:['mem2050','dataBus','MDR'],move:{from:[775,380],to:[542,160],text:'03H',kind:'data'},set:{MDR:'03H'},caption:'The CPU now has both values needed for addition: ACC = 05H and MDR = 03H.'},
{phase:'EXECUTE',title:'Bring both operands to the ALU',text:'The accumulator supplies 05H and MDR supplies 03H. The ALU can perform many operations, so it still needs one more instruction from the Control Unit.',micro:'ALU input A ← ACC = 05H\nALU input B ← MDR = 03H',active:['ACC','MDR','ALU'],set:{ALU:'05H  ?  03H'},caption:'The ALU has the numbers — but has not yet decided what to do with them.'},
{phase:'EXECUTE',title:'Who tells the ALU to ADD?',text:'The Control Unit decoded the opcode earlier. It now activates the ALU ADD operation.',micro:'CU → ALU CONTROL = ADD',active:['CU','ALU'],move:{from:[425,330],to:[424,410],text:'ADD',kind:'control'},set:{CU:'ALU = ADD'},caption:'Important: the ALU does not choose the operation. The Control Unit selects it.'},
{phase:'EXECUTE',title:'The ALU performs the addition',text:'Now the arithmetic operation actually happens.',micro:'  05H\n+ 03H\n─────\n  08H',active:['ALU'],set:{ALU:'08H'},caption:'05H + 03H = 08H.'},
{phase:'WRITEBACK',title:'Store the result in ACC',text:'The ALU output is written back to the accumulator, replacing its old value.',micro:'ACC ← ALU result\nACC: 05H → 08H',active:['ALU','ACC'],move:{from:[424,470],to:[150,450],text:'08H',kind:'data'},set:{ACC:'08H'},caption:'Instruction complete ✓  ACC now contains 08H.'},
{phase:'WRITEBACK',title:'You just operated the CPU',text:'One ADD instruction required an instruction fetch, decode, operand fetch, ALU control and write-back.',micro:'FETCH → DECODE → FETCH OPERAND → EXECUTE → WRITE BACK\n\nACC ← ACC + Memory[2050H]\n05H + 03H = 08H',active:['PC','MAR','MDR','IR','CU','ACC','ALU'],caption:'Replay it until you can predict the next micro-operation before pressing Next.'}
];
function resetState(){Object.assign(state,{PC:'1000H',MAR:'—',MDR:'—',IR:'—',CU:'waiting',ACC:'05H',ALU:'—'});}
function sync(){for(const k of ['PC','MAR','MDR','IR','CU','ACC','ALU']) $('#'+k+'val').textContent=state[k];}
function clearActive(){$$('.active').forEach(x=>x.classList.remove('active'));}
function phase(p){$$('.phasebar div').forEach(x=>x.classList.toggle('active',x.dataset.phase===p));}
function wait(ms){return new Promise(r=>setTimeout(r,ms));}
async function packetMove(m){if(!m)return;busy=true;const p=$('#packet'),t=$('#packetText');p.classList.remove('hidden','address','data','control');p.classList.add(m.kind);t.textContent=m.text;const [x1,y1]=m.from,[x2,y2]=m.to;p.setAttribute('transform',`translate(${x1-45} ${y1-17})`);p.style.opacity='1';await wait(30);const dur=850*Number($('#speed').value);p.style.transition=`transform ${dur}ms cubic-bezier(.4,0,.2,1)`;p.setAttribute('transform',`translate(${x2-45} ${y2-17})`);await wait(dur+80);p.style.opacity='0';await wait(120);p.classList.add('hidden');p.style.transition='none';busy=false;}
function buildQuestion(q){const box=$('#question');if(!q){box.classList.add('hidden');box.innerHTML='';$('#nextBtn').disabled=false;return}box.classList.remove('hidden');box.innerHTML=`<b>${q.prompt}</b>`;$('#nextBtn').disabled=true;q.choices.forEach((c,i)=>{const b=document.createElement('button');b.textContent=c;b.onclick=()=>{if(i===q.answer){b.classList.add('correct');b.textContent+='  ✓ Correct';[...box.querySelectorAll('button')].forEach(x=>x.disabled=true);$('#nextBtn').disabled=false}else{b.classList.add('wrong');b.textContent+='  Try again'}};box.appendChild(b)});}
async function render(animate=true){const s=steps[step];clearActive();phase(s.phase);$('#stepNo').textContent=`STEP ${step+1} OF ${steps.length} · ${s.phase}`;$('#stepTitle').textContent=s.title;$('#stepText').textContent=s.text;$('#micro').textContent=s.micro;$('#caption').textContent=s.caption;s.active.forEach(id=>$('#'+id)?.classList.add('active'));buildQuestion(s.question);if(animate&&s.move)await packetMove(s.move);if(s.set)Object.assign(state,s.set);sync();$('#prevBtn').disabled=step===0;$('#nextBtn').textContent=step===steps.length-1?'Restart lesson ↻':'Next micro-operation →';}
function reconstruct(n){resetState();for(let i=0;i<=n;i++)if(steps[i].set)Object.assign(state,steps[i].set);sync();}
$('#nextBtn').onclick=async()=>{if(busy)return;if(step===steps.length-1){step=0;resetState();await render(false);return}step++;await render(true)};
$('#prevBtn').onclick=()=>{if(busy||step===0)return;step--;reconstruct(step);render(false)};
$('#replayBtn').onclick=()=>{if(!busy)render(true)};
function start(){step=0;resetState();render(false);$('#lab').scrollIntoView({behavior:'smooth'});}$('#startBtn').onclick=start;$('#restartTop').onclick=start;
resetState();render(false);
